using System;
using System.Collections.Generic;
using AutoTrade.Services.Database;

namespace Database
{
    public static class DefaultAutomobileAdData
    {
        public static IEnumerable<AutomobileAd> AutomobileAds
        
        {
             get => new List<AutomobileAd>()
            {
                new AutomobileAd
                {
                    Id = 1,
                    Title = "Audi A3 2018",
                    Description = "Audi A3 u odličnom stanju, dobro održavan, prvi vlasnik.",
                    Price = 25000,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 230,
                    YearOfManufacture = 2018,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2024, 5, 30),
                    Status = "Active",
                    Milage = 75000,
                    UserId = 1,
                    CarBrandId = 1,
                    CarCategoryId = 1,
                    CarModelId = 1,
                    FuelTypeId = 1,
                    TransmissionTypeId = 2,
                    EnginePower = 140,
                    NumberOfDoors = 4,
                    CubicCapacity = 2000,
                    HorsePower = 190,
                    Color = "Crna",
                    VehicleConditionId = 2,
                    IsHighlighted = true,
                    HighlightExpiryDate = DateTime.Now.AddDays(2)
                },
                //2
                new AutomobileAd
                {
                    Id = 2,
                    Title = "Audi a3 s line",
                    Description = "audi a3 sa odličnim performansama, drugi vlasnik. S line oprema sve u fullu uradjeno. Crno nebo",
                    Price = 20000,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 123,
                    YearOfManufacture = 2015,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2024, 6, 15),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2023,11,11),
                    Status = "Active",
                    Milage = 123223,
                    UserId = 2,
                    CarBrandId = 9,
                    CarCategoryId = 1,
                    CarModelId = 33,
                    FuelTypeId = 2,
                    TransmissionTypeId = 1,
                    EnginePower = 120,
                    NumberOfDoors = 4,
                    CubicCapacity = 1,
                    HorsePower = 184,
                    Color = "Bijela",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                //3
                    new AutomobileAd
                {
                    Id = 3,
                    Title = "Audi A4 B8 Karavan 2015",
                    Description = "Audi A4 u odličnom stanju, dobro održavan, drugo vlasnik. Karavan jako ocuvan sa puno dodatne opreme",
                    Price = 13450,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 30,
                    YearOfManufacture = 2015,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2024, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2023,11,11),
                    Status = "Active",
                    Milage = 230121,
                    UserId = 3,
                    CarBrandId = 9,
                    CarCategoryId = 2,
                    CarModelId = 32,
                    FuelTypeId = 2,
                    TransmissionTypeId = 1,
                    EnginePower = 140,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 120,
                    Color = "Crna",
                    VehicleConditionId = 2,
                    IsHighlighted = false,
                },
                //4
                 new AutomobileAd
                {
                    Id = 4,
                    Title = "Audi A5",
                    Description = "Audi A5 u odličnom stanju, dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi",
                    Price = 16500,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 39,
                    YearOfManufacture = 2018,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2024, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2023,11,11),
                    Status = "Active",
                    Milage = 230121,
                    UserId = 4,
                    CarBrandId = 9,
                    CarCategoryId = 1,
                    CarModelId = 31,
                    FuelTypeId = 2,
                    TransmissionTypeId = 1,
                    EnginePower = 140,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 120,
                    Color = "Bijela",
                    VehicleConditionId = 2,
                    IsHighlighted = false,
                },
                //5
                  new AutomobileAd
                {
                    Id = 5,
                    Title = "Audi A6",
                    Description = "Audi A6 u odličnom stanju, dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 22500,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 123,
                    YearOfManufacture = 2020,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 120121,
                    UserId = 5,
                    CarBrandId = 9,
                    CarCategoryId = 1,
                    CarModelId = 33,
                    FuelTypeId = 2,
                    TransmissionTypeId = 1,
                    EnginePower = 140,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 190,
                    Color = "Siva",
                    VehicleConditionId = 2,
                    IsHighlighted = true,
                    HighlightExpiryDate = DateTime.Now.AddDays(20)
                },
                //6
                    new AutomobileAd
                {
                    Id = 6,
                    Title = "BMW E60",
                    Description = "BMW E60 u odličnom stanju, dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 10500,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 250,
                    YearOfManufacture = 2010,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 450301,
                    UserId = 6,
                    CarBrandId = 8,
                    CarCategoryId = 1,
                    CarModelId = 24,
                    FuelTypeId = 1,
                    TransmissionTypeId = 2,
                    EnginePower = 88,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 190,
                    Color = "Smedja",
                    VehicleConditionId = 2,
                    IsHighlighted = false,
                },
                //7
                new AutomobileAd
                {
                    Id = 7,
                    Title = "Citroen DS 5",
                    Description = "Citroen ds 6 u odličnom stanju, dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 6000,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 10,
                    YearOfManufacture = 2009,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 290421,
                    UserId = 7,
                    CarBrandId = 13,
                    CarCategoryId = 1,
                    CarModelId = 16,
                    FuelTypeId = 1,
                    TransmissionTypeId = 2,
                    EnginePower = 104,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 88,
                    Color = "Plava",
                    VehicleConditionId = 2,
                    IsHighlighted = false,
                },
                //8
                  new AutomobileAd
                {
                    Id = 8,
                    Title = "Fiat punto",
                    Description = "Fiat punto u odličnom stanju, dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 3500,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 11,
                    YearOfManufacture = 2004,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 542121,
                    UserId = 8,
                    CarBrandId = 15,
                    CarCategoryId = 1,
                    CarModelId = 48,
                    FuelTypeId = 1,
                    TransmissionTypeId = 2,
                    EnginePower = 44,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 88,
                    Color = "Crna",
                    VehicleConditionId = 3,
                    IsHighlighted = false,
                },
                   //9
                   new AutomobileAd
                {
                    Id = 9,
                    Title = "Golf 4",
                    Description = "Golf 4 u perfektnom stanju, dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 5800,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 300,
                    YearOfManufacture = 2002,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 321211,
                    UserId = 9,
                    CarBrandId = 2,
                    CarCategoryId = 1,
                    CarModelId = 6,
                    FuelTypeId = 1,
                    TransmissionTypeId = 2,
                    EnginePower = 88,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 88,
                    Color = "Siva",
                    VehicleConditionId = 2,
                    IsHighlighted = false,
                },
                //10
                   new AutomobileAd
                {
                    Id = 10,
                    Title = "Golf 6 GTD",
                    Description = "Golf 6 GTD u perfektnom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 18500,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 550,
                    YearOfManufacture = 2016,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 234012,
                    UserId = 10,
                    CarBrandId = 2,
                    CarCategoryId = 1,
                    CarModelId = 6,
                    FuelTypeId = 1,
                    TransmissionTypeId = 2,
                    EnginePower = 180,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 210,
                    Color = "Crna",
                    VehicleConditionId = 2,
                    IsHighlighted = false,
                },
                //11
                new AutomobileAd
                {
                    Id = 11,
                    Title = "Golf 7",
                    Description = "Golf 7 u perfektnom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 19900,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 123,
                    YearOfManufacture = 2012,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 234012,
                    UserId = 1,
                    CarBrandId = 2,
                    CarCategoryId = 1,
                    CarModelId = 6,
                    FuelTypeId = 1,
                    TransmissionTypeId = 2,
                    EnginePower = 180,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 210,
                    Color = "Crna",
                    VehicleConditionId = 2,
                    IsHighlighted = true,
                    HighlightExpiryDate = DateTime.Now.AddDays(20)
                },
                //12
                 new AutomobileAd
                {
                    Id = 12,
                    Title = "Golf 7 Tdi",
                    Description = "Golf 7 TDI u perfektnom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 17800,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 231,
                    YearOfManufacture = 2014,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 215012,
                    UserId = 2,
                    CarBrandId = 2,
                    CarCategoryId = 1,
                    CarModelId = 6,
                    FuelTypeId = 1,
                    TransmissionTypeId = 2,
                    EnginePower = 180,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 210,
                    Color = "Siva",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                //13
                    new AutomobileAd
                {
                    Id = 13,
                    Title = "Hyundai Kona",
                    Description = "Hyundai Kona TDI u perfektnom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 24100,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 333,
                    YearOfManufacture = 2020,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 123444,
                    UserId = 2,
                    CarBrandId = 10,
                    CarCategoryId = 1,
                    CarModelId = 36,
                    FuelTypeId = 2,
                    TransmissionTypeId = 1,
                    EnginePower = 100,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 100,
                    Color = "Crvena",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                //14
                    new AutomobileAd
                {
                    Id = 14,
                    Title = "Land Rover",
                    Description = "Land Roveru perfektnom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 13500,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 231,
                    YearOfManufacture = 2011,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 450000,
                    UserId = 3,
                    CarBrandId = 28,
                    CarCategoryId = 1,
                    CarModelId = 47,
                    FuelTypeId = 2,
                    TransmissionTypeId = 2,
                    EnginePower = 150,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 144,
                    Color = "Bež",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                  //15
                    new AutomobileAd
                {
                    Id = 15,
                    Title = "Mazda cx 7",
                    Description = "Mazda cx7 u perfektnom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 9500,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 50,
                    YearOfManufacture = 2008,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 450000,
                    UserId = 4,
                    CarBrandId = 24,
                    CarCategoryId = 1,
                    CarModelId = 36,
                    FuelTypeId = 1,
                    TransmissionTypeId = 3,
                    EnginePower = 150,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 144,
                    Color = "Bijela",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                //16
                    new AutomobileAd
                {
                    Id = 16,
                    Title = "Mercedes ML 350",
                    Description = "Mercedes ML 350 u perfektnom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 11200,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 55,
                    YearOfManufacture = 2010,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 300000,
                    UserId = 5,
                    CarBrandId = 7,
                    CarCategoryId = 1,
                    CarModelId = 26,
                    FuelTypeId = 5,
                    TransmissionTypeId = 1,
                    EnginePower = 150,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 144,
                    Color = "Siva",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                     //17
                    new AutomobileAd
                {
                    Id = 17,
                    Title = "Opel Corsa 1.3",
                    Description = "Open Corsa 1.2 u dobrom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 5400,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 35,
                    YearOfManufacture = 2005,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 348400,
                    UserId = 6,
                    CarBrandId = 16,
                    CarCategoryId = 1,
                    CarModelId = 2,
                    FuelTypeId = 3,
                    TransmissionTypeId = 1,
                    EnginePower = 110,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 150,
                    Color = "Plava",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                    //18
                    new AutomobileAd
                {
                    Id = 18,
                    Title = "Passat b6",
                    Description = "Passat b6 u dobrom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 6600,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 90,
                    YearOfManufacture = 2004,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 448400,
                    UserId = 7,
                    CarBrandId = 2,
                    CarCategoryId = 1,
                    CarModelId = 7,
                    FuelTypeId = 5,
                    TransmissionTypeId = 2,
                    EnginePower = 110,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 150,
                    Color = "Siva",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                    //19
                    new AutomobileAd
                {
                    Id = 19,
                    Title = "Passat CC",
                    Description = "Passat CC u dobrom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 21000,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 123,
                    YearOfManufacture = 2019,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 245131,
                    UserId = 8,
                    CarBrandId = 2,
                    CarCategoryId = 1,
                    CarModelId = 7,
                    FuelTypeId = 5,
                    TransmissionTypeId = 2,
                    EnginePower = 110,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 150,
                    Color = "Crna",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                 //20
                    new AutomobileAd
                {
                    Id = 20,
                    Title = "Peugeot 407",
                    Description = "Peugeot 407 u dobrom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 3500,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 222,
                    YearOfManufacture = 2001,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 545131,
                    UserId = 9,
                    CarBrandId = 12,
                    CarCategoryId = 1,
                    CarModelId = 7,
                    FuelTypeId = 5,
                    TransmissionTypeId = 1,
                    EnginePower = 88,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 110,
                    Color = "Siva",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                //21
                     new AutomobileAd
                {
                    Id = 21,
                    Title = "Polo 2006",
                    Description = "Polo 2006 u dobrom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 4300,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 111,
                    YearOfManufacture = 2002,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 345000,
                    UserId = 10,
                    CarBrandId = 2,
                    CarCategoryId = 1,
                    CarModelId = 7,
                    FuelTypeId = 1,
                    TransmissionTypeId = 1,
                    EnginePower = 88,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 110,
                    Color = "Plava",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                    //22
                    new AutomobileAd
                {
                    Id = 22,
                    Title = "Quad",
                    Description = "Quad u dobrom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 14000,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 30,
                    YearOfManufacture = 2009,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 55000,
                    UserId = 2,
                    CarBrandId = 47,
                    CarCategoryId = 6,
                    CarModelId = 41,
                    FuelTypeId = 1,
                    TransmissionTypeId = 1,
                    EnginePower = 88,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 110,
                    Color = "Crna",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                 //23
                    new AutomobileAd
                {
                    Id = 23,
                    Title = "Renault Megan",
                    Description = "Renault Megan u dobrom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 3500,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 35,
                    YearOfManufacture = 2004,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 250111,
                    UserId = 3,
                    CarBrandId = 13,
                    CarCategoryId = 2,
                    CarModelId = 2,
                    FuelTypeId = 1,
                    TransmissionTypeId = 1,
                    EnginePower = 140,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 103,
                    Color = "Plava",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                //24
                      new AutomobileAd
                {
                    Id = 24,
                    Title = "Renault Scenic",
                    Description = "Renault Scenic u dobrom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 3500,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 35,
                    YearOfManufacture = 2004,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 250111,
                    UserId = 4,
                    CarBrandId = 17,
                    CarCategoryId = 1,
                    CarModelId = 5,
                    FuelTypeId = 1,
                    TransmissionTypeId = 1,
                    EnginePower = 140,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 103,
                    Color = "Plava",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                 //25
                 new AutomobileAd
                {
                    Id = 25,
                    Title = "Skoda Octavia HTP",
                    Description = "Skoda fabia HTP u dobrom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 5000,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 55,
                    YearOfManufacture = 20014,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 250111,
                    UserId = 5,
                    CarBrandId = 17,
                    CarCategoryId = 2,
                    CarModelId = 2,
                    FuelTypeId = 1,
                    TransmissionTypeId = 1,
                    EnginePower = 140,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 103,
                    Color = "Plava",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                //26
                    new AutomobileAd
                {
                    Id = 26,
                    Title = "Skoda Octavia",
                    Description = "Skoda Octavia 1.2 u dobrom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 5000,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 55,
                    YearOfManufacture = 20014,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 350000,
                    UserId = 6,
                    CarBrandId = 17,
                    CarCategoryId = 2,
                    CarModelId = 2,
                    FuelTypeId = 1,
                    TransmissionTypeId = 1,
                    EnginePower = 140,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 103,
                    Color = "Bijela",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                //27
                     new AutomobileAd
                {
                    Id = 27,
                    Title = "WV bora",
                    Description = "Bora  u dobrom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 11000,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 142,
                    YearOfManufacture = 20014,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 450131,
                    UserId = 6,
                    CarBrandId = 2,
                    CarCategoryId = 1,
                    CarModelId = 15,
                    FuelTypeId = 1,
                    TransmissionTypeId = 1,
                    EnginePower = 140,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 103,
                    Color = "Bijela",
                    VehicleConditionId = 2,
                    IsHighlighted = false
                },
                //28
                    new AutomobileAd
                {
                    Id = 28,
                    Title = "Tiguan",
                    Description = "Tiguran u dobrom stanju, Auto koje puno trosi al se zna za sta se placa, VR 6 motor,dobro održavan nove 4 gume zimske i ljetne, drugi vlasnik.Jako ocuvan sa puno dodatne opreme auto bez packe sjedi i vozi. Najbolje doci i pogledati auto. Vozeno na posao i nazad. Nov akumulator i set kvacila odradjen nedavno.!!!PRODAJA SAMO",
                    Price = 11000,
                    DateOFadd = DateTime.Now,
                    ViewsCount = 541,
                    YearOfManufacture = 20014,
                    Registered = true,
                    RegistrationExpirationDate = new DateTime(2025, 5, 30),
                    FeaturedExpiryDate = new DateTime(2025,1,20),
                    Last_Small_Service = new DateTime(2024,5,4),
                    Last_Big_Service = new DateTime(2024,11,11),
                    Status = "Active",
                    Milage = 222000,
                    UserId = 6,
                    CarBrandId = 2,
                    CarCategoryId = 6,
                    CarModelId = 9,
                    FuelTypeId = 1,
                    TransmissionTypeId = 1,
                    EnginePower = 190,
                    NumberOfDoors = 4,
                    CubicCapacity = 2,
                    HorsePower = 103,
                    Color = "Bijela",
                    VehicleConditionId = 2,
                    IsHighlighted = true,
                    HighlightExpiryDate = DateTime.Now.AddDays(20)
                },
            };
        }
             
    }
}
