name: desktop_app
description: A new Flutter project for desktop.

publish_to: "none" # Ne objavljuješ ovaj projekat na pub.dev.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  http: ^1.2.2
  fluttertoast: ^8.2.1
  image_picker: ^0.8.7
  photo_view: ^0.14.0
  intl: ^0.18.0
  dropdown_button2: ^2.1.3
  fl_chart: ^0.62.0
  flutter_dotenv: ^5.0.2
  flutter_stripe: ^11.3.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  - .env